#PBS -l nodes=8:ppn=8,mem=20gb,walltime=00:15:00

#
# Job Pre Processing
source $PBS_O_WORKDIR/../setup_env.sh
cd $PBS_O_WORKDIR

# Run program
mpirun -np 1 psum_mpi 10000000 0
mpirun -np 4 psum_mpi 10000000 0
mpirun -np 6 psum_mpi 10000000 0
mpirun -np 12 psum_mpi 10000000 0
mpirun -np 24 psum_mpi 10000000 0
mpirun -np 48 psum_mpi 10000000 0
mpirun -np 64 psum_mpi 10000000 1

# Post Processing
